<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tp3ratings"
 *
 * Auto generated by Extension Builder 2017-11-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Tp3Ratings',
    'description' => 'Ratings for Webpages including microdata for google',
    'category' => 'plugin',
    'author' => 'Thomas Ruta',
    'author_email' => 'email@thomasruta.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.6',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
